version: 1.0.{build}
image: Ubuntu

services:
- docker

install:
- sh: sudo apt-get update -y -qq
- sh: sudo apt-get install -y qemu-user-static
- sh: sudo apt-get install -y binfmt-support

build_script:
- sh: docker build -t tvm_jetson .
