version: 1.0.{build}
image: Ubuntu2004

environment:
  matrix:
    - ARCH: arm64

install:
- sh: sudo apt-get update
- sh: sudo apt-get install -y qemu-user-static
- sh: sudo apt-get install -y binfmt-support

services:
- docker

build_script:
  - sh: docker run --rm --entrypoint '/bin/bash' abhilb/tvm_jetson:latest -c ./build.sh
