name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 420

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y qemu-user-static
          sudo apt-get install -y binfmt-support

      - name: Test
        run: |
          docker run --rm abhilb/tvm_jetson_base:latest
